<?php ob_start(); ?>
<h2>Affichage du QCM</h2>

<?php foreach($questions as $cle => $question): ?>
    <section class="consulter p-2">
        <div class="mt-3 d-flex justify-content-between mr-5">
            <?= htmlentities($question->question); ?>
            <div>
                <a href="?action=edit&id=<?= intval($question->id) ?>" class=""><i class="fas fa-edit"></i></a>
                <a href="?action=delete&id=<?= intval($question->id) ?>" class=""><i class="fas fa-trash"></i></a>
            </div>
        </div>
        <?php for ($i = $compteur; $i < (3+$next); $i++): ?>
            <div class="ml-5"> <?= htmlentities($reponses[$i]->reponse); ?> </div>
            <?php $compteur++;?>
        <?php endfor; ?>
    </section>
    <?php $next +=3; ?>
<?php endforeach; ?>


<?php $content = ob_get_clean();

include 'template.phtml';