<?php ob_start(); ?>
<h2>Déposer une question/réponses</h2>

<form action="" method="post">
    <input type="hidden" name="id" value="<?= isset($question) ? $question->id : '' ?>" >
    <div class="form-group">
        <label for="">Thème </label>
        <input type="text" name="theme" class="form-control" placeholder="Theme" value="<?= isset($question) ? $question->theme : '' ?>">
    </div>

    <div class="form-group">
        <label for="">Question </label>
        <input type="text" name="question" class="form-control" placeholder="question" value="<?= isset($question) ? $question->question : '' ?>">
    </div>

    <?php for($i = 1; $i <= 3; $i++): ?>
        <input type="hidden" name="id_reponse_<?= $i ?>" value="<?= isset($reponse) ? $reponse[$i-1]->id : '' ?>" >
        <div class="form-group">
            <label for="">Proposition <?= $i ?> </label>
            <input type="text" value="<?= isset($reponse) ? $reponse[$i-1]->reponse : '' ?>" name="proposition_<?= $i ?>" class="form-control" placeholder="Proposition <?= $i ?>">
        </div>
    <?php endfor; ?>

    <label for="">Choisir le marqueur</label>
    <?php for($i = 1; $i <= 3; $i++): ?>
        <div class="form-check">
            <input type="radio" <?= (isset($reponse) && 1 == $reponse[$i-1]->marqueur) ? 'checked' : '' ?> name="marqueur" class="form-check-input" value="rep_<?= $i ?>" id="proposition_<?= $i ?>">
            <label class="form-check-label" for="proposition_<?= $i ?>">proposition <?= $i ?></label>
        </div>
    <?php endfor; ?>
    <input type="hidden" name="auteur" value="<?= unserialize($_SESSION['personne'])->id ?>">

    <input type="submit" class="btn btn-primary mt-2" name="inscription">
</form>

<?php $content = ob_get_clean();

include 'template.phtml';