<?php ob_start(); ?>
<h2>Inscription</h2>

<form action="" method="post">
    <input type="hidden" name="id" value="<?= isset($personne) ? $personne->id : '' ?>">
    <div class="form-group">
        <label for="">Nom </label>
        <input type="text" name="nom" class="form-control" value="<?= isset($personne) ? $personne->nom : '' ?>" placeholder="Nom">
    </div>

    <div class="form-group">
        <label for="">Mail </label>
        <input type="email" name="mail" class="form-control" value="<?= isset($personne) ? $personne->mail : '' ?>" placeholder="Mail">
    </div>

    <div class="form-group">
        <label for="">Login </label>
        <input type="text" name="login" class="form-control" value="<?= isset($personne) ? $personne->login : '' ?>" placeholder="Login">
    </div>

    <div class="<?= isset($personne) ? 'd-none' :'' ?>">
        <div class="form-group">
            <label for="">Mot de passe </label>
            <input type="password" name="mdp" class="form-control" placeholder="password">
        </div>

        <div class="form-group">
            <label for="">Confirmer mot de passe </label>
            <input type="password" name="confirm" class="form-control" placeholder="confirm password">
        </div>
    </div>
    <input type="submit" class="btn btn-primary" name="inscription">
</form>

<?php $content = ob_get_clean();

include 'template.phtml';