<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/style.css">
    <title>Document</title>
</head>
<body>
    <header class="jumbotron">

        <nav class="d-flex justify-content-around">
            <a href=".">HOME</a>
            <?php if(isset($_SESSION['personne'])): ?>
                <?php if( unserialize($_SESSION['personne'])->statut == 'prof' ): ?>
                    <a href="?action=user&id=<?= unserialize($_SESSION['personne'])->id ?>"><i class="fas fa-user-edit"></i></a>
                    <a href="?action=deposer">Déposer</a>
                    <a href="?action=consulter">Consulter</a>
<!--                    <a href="?action=modifier">Modifier</a>-->
<!--                    <a href="?action=supprimer">Supprimer</a>-->
                <?php endif; ?>
                <a href="?action=lire">Lire/remplir</a>
                <a href="?action=resultats">Résultats</a>
                <a href="?action=deconnexion">Déconnexion</a>
            <?php else: ?>
                <a href="?action=connexion">Connexion</a>
                <a href="?action=inscription">Incription</a>
            <?php endif; ?>
        </nav>
    </header>

    <main class="container-fluid mb-3">
        <?=  $content ?? "" ?>
    </main>

    <footer>

    </footer>


</body>
</html>