<?php


class Reponse extends Generique
{
    protected $id;
    protected $reponse;
    protected $marqueur;
    protected $question;

    public function __construct($data = [])
    {
        parent::__construct($data); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getReponse()
    {
        return $this->reponse;
    }

    /**
     * @param mixed $reponse
     */
    public function setReponse($reponse)
    {
        $this->reponse = $reponse;
    }

    /**
     * @return mixed
     */
    public function getMarqueur()
    {
        return $this->marqueur;
    }

    /**
     * @param mixed $marqueur
     */
    public function setMarqueur($marqueur)
    {
        $this->marqueur = $marqueur;
    }

    /**
     * @return mixed
     */
    public function getQuestion()
    {
        return $this->question;
    }

    /**
     * @param mixed $id_question
     */
    public function setQuestion($idQuestion)
    {
        $this->question = $idQuestion;
    }


}